### ISSUE TITLE
FERNET_KEY configuration missing

### ISSUE THREAD

**Issue by gfelot** [godatadriven-dockerhub/airflow#6]
I add a variable to the UI that's automatically encrypted.
The when I run my dag it fails :
`Can't decrypt _val for key=s3_bucket, FERNET_KEY configuration missing`

I went into my docker and look at the `airflow.cfg` file where I can see : 
> Secret key to save connection passwords in the db
fernet_key = XdGcyNWX7XXXXXXXXXXX=

Any idea ?

**Comment by NielsZeilemaker** [comment]
Did you mount the airflow.cfg file to both the webserver and the scheduler?

**Comment by gfelot** [comment]
Yes on both.
```
volumes:
      [...]
      - ./airflow.cfg:/root/airflow/airflow.cfg
```

But it's seems that I need to install the package `cryptography`. I'm trying that right now.

EDIT: Even after installing the lib I'm faving the issue.
EDIT2: I had to install the `cryptography`, drop the db (since scheduler and webserver have their on values), mount the same `.cfg` for both to share the same FernetKey, restart my docker-compose. Good for now.

**Comment by NielsZeilemaker** [comment]
Did installing cryptography fix it?

Op vr 9 aug. 2019 17:55 schreef Gil <notifications@github.com>:

**Comment by gfelot** [comment]
Yep and removing the data in the db because once the fernet_key set you cannot overwrite it, or I don't know how to do it. Even a `init_db` didn't work. I rm the airflow tables after installing the lib from `environment.yml` AND sharing the same `*.cfg` file to both instance.

**Comment by NielsZeilemaker** [comment]
The `reset_db` command will allow you to remove all the content of your
database. No need to rm them.

Op vr 9 aug. 2019 19:11 schreef Gil <notifications@github.com>:

**Comment by gfelot** [comment]
I didn't see this command. Where can I have more info ?

**Comment by NielsZeilemaker** [comment]
https://airflow.apache.org/cli.html#resetdb

Op vr 9 aug. 2019 19:24 schreef Gil <notifications@github.com>:

**Comment by gfelot** [comment]
My bad I thought it was something you buildin the docker image. Thanks.
