### ISSUE TITLE
Issue with Module path for Operators

### ISSUE THREAD

**Issue by gfelot** [godatadriven-dockerhub/airflow#7]
I'm opening here an issue since I don't know if it's linked to the way this docker is made or if it's my use of it.

I just wrote a S/O question here : https://stackoverflow.com/questions/58237543/airflow-on-docker-path-issue

If some of the contributors here can give me a hand ? 

Thanks.

**Comment by NielsZeilemaker** [comment]
Hi Gil, I would not recommend the plugin approach. Typically I would structure your dags folder as follows:
```
├── airflow.cfg
├── dags
│   ├── dag.py
│   └── sql_statements.sql
│   └── facts_calculator.py
│   └── has_rows.py
│   └── s3_to_redshift.py
├── docker-compose.yaml
├── environment.yml
```
or create a subfolder in the dags folder containing your custom hooks.

**Comment by gfelot** [comment]
But the `plugins approach` is the recommanded approach on the doc and on every tutorial I have read so far : https://airflow.apache.org/plugins.html

**Comment by NielsZeilemaker** [comment]
Probably you're right, but I typically have a look at the source code of airflow first, and then make a decision if something is a good approach.
And looking at the `plugin_mananger.py` I get a bit scared by the use of the `imp` package.

**Comment by gfelot** [comment]
So you write your customs plugins (Operators, Hooks...) in the dags folder ?
Then how do you import them ?

Do you have a dump working exemple to share ?

**Comment by gfelot** [comment]
Also, not skilled enough to be scare by the `imp` package, what's wrong with that ?

**Comment by NielsZeilemaker** [comment]
It's more a gut feeling, I don't like manipulating my path to be able to import package from a different directory. From a dag do something like this:
```
from hooks import XYZHook
```
That should work if you have a `hooks.py` file in your dags folder.

**Comment by gfelot** [comment]
Ok I can from there make a `operators` or a `hooks` folder just to have a clean structure.

**Comment by gfelot** [comment]
@NielsZeilemaker 
I change my project structure like :
```
├── dags
│   ├── __init__.py
│   ├── dag.py
│   ├── operators
│   │   ├── __init__.py
│   │   ├── facts_calculator.py
│   │   ├── has_rows.py
│   │   └── s3_to_redshift.py
│   └── sql_statements.py
[...]
```

I still have the issue :

```
[2019-10-04 14:40:13,028] {dagbag.py:205} ERROR - Failed to import: /root/airflow/dags/dag.py
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/airflow/models/dagbag.py", line 202, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/opt/miniconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/airflow/dags/dag.py", line 5, in <module>
    from dags.operators import HasRowsOperator, S3ToRedshiftOperator
ModuleNotFoundError: No module named 'dags'
```

**Comment by NielsZeilemaker** [comment]
I would remove the `__init__.py` file from the dags folder, and just do `from operators import HasRowOper....`
